version: '3.8'

networks:
  mon_reseau:

services:
  adminer:
    build:
      context: ./docker/adminer
    ports:
      - "8080:8080"
    networks:
      - mon_reseau

  postgres:
    build:
      context: ./docker/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    ports:
      - "5432:5432"
    networks:
      - mon_reseau

  symfony:
    build:
      context: ./docker/symfony
    volumes:
      - ./app/symfony:/var/www/symfony
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - mon_reseau

  composer:
    image: composer:latest
    volumes:
      - ./symfony:/app
    command: ["install"]
    networks:
      - mon_reseau

volumes:
  postgres_data:

