version: '3.8'

services:
  adminer:
    build:
      context: ./docker/adminer
    ports:
      - "8080:8080"

  composer:
    image: composer:latest
    build:
      context: ./docker/composer
    volumes:
      - ./symfony:/app

  postgres:
    build:
      context: ./docker/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    ports:
      - "5432:5432"

  symfony:
    build:
      context: ./docker/symfony
    volumes:
      - ./symfony:/var/www/symfony
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres_data:
